### ISSUE TITLE
Missing default constructor

### ISSUE THREAD

**Issue by matt77hias** [PeterSommerlad/scope17#12]
According to the documentation at https://en.cppreference.com/w/cpp/experimental/unique_resource/unique_resource, this version seems to be missing the default constructor `std::experimental::unique_resource`:

Default constructor. Value-initializes the stored resource handle and the deleter. The constructed unique_resource does not own the resource. This overload only participates in overload resolution if both `std::is_default_constructible_v<R>` and `std::is_default_constructible_v<D>` are `true`.

_Is this supposed to be the most up-to-date platform independent version or is there another repository?_

**Comment by PeterSommerlad** [comment]
Thanks for your question, I stopped working on the proposal, because I was frustrated about how it was treated over the many years. I also think the requirements for a default constructor are wrong. The resource will not be initialized, because the unique_resource object starts disengaged. I might try a more modern implementation using std::optional<R> in the future and see where that leads. Also some other issues have been pointed out, such as initialization of the unique_resource object failing and thus potential leaks happening, e.g., instead of passing the resource in, passing the factory as argument to unique_resource's constructor.
